In [3]:
import pandas as pd

df = pd.read_csv('seoul_real_estate_m.csv')

df

C:\Users\crazy\AppData\Local\Temp\ipykernel_22424\67291803.py:3: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('seoul_real_estate_m.csv')

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2024,11230,동대문구,11000,이문동,1.0,대지,0311,0000,래미안이문2차,...,70500,59.79,0.00,2.0,NaN,20240406.0,2004.0,아파트,중개거래,서울 동대문구
1,2024,11710,송파구,10800,문정동,1.0,대지,0652,0001,프라비다옥토,...,18000,19.74,29.29,8.0,NaN,NaN,2016.0,오피스텔,직거래,NaN
2,2024,11620,관악구,10200,신림동,1.0,대지,1572,0013,금호맨션9차,...,30000,60.44,30.64,3.0,NaN,NaN,2002.0,연립다세대,중개거래,서울 관악구
3,2024,11410,서대문구,11100,홍제동,1.0,대지,0331,0000,홍제현대,...,74600,75.15,0.00,8.0,NaN,NaN,1992.0,아파트,중개거래,서울 서대문구
4,2024,11110,종로구,18300,평창동,1.0,대지,0046,0001,크래스빌,...,102000,175.81,0.00,2.0,NaN,NaN,2003.0,아파트,중개거래,서울 종로구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,2022,11560,영등포구,12600,양평동2가,1.0,대지,43.0,14.0,CO-OP Residence/오목교,...,7400,16.98,26.58,5.0,NaN,NaN,2004.0,오피스텔,중개거래,서울 영등포구
99996,2022,11620,관악구,10100,봉천동,1.0,대지,1591.0,2.0,서울대입구삼성,...,75000,59.78,0.00,13.0,NaN,NaN,1999.0,아파트,중개거래,서울 관악구
99997,2022,11500,강서구,10400,가양동,1.0,대지,1479.0,8.0,동양 트레벨 스카이 오피스텔,...,12000,26.96,40.46,5.0,NaN,NaN,2003.0,오피스텔,중개거래,서울 강서구
99998,2022,11680,강남구,10800,논현동,1.0,대지,58.0,2.0,마일스디오빌,...,37800,36.29,0.00,3.0,NaN,NaN,2004.0,아파트,중개거래,서울 강남구
99999,2022,11710,송파구,10600,삼전동,1.0,대지,168.0,21.0,BeART,...,67000,88.21,46.58,4.0,NaN,NaN,2002.0,연립다세대,중개거래,서울 송파구

In [4]:
df['DEAL_YMD'] = pd.to_datetime(df['DEAL_YMD'])
df['month'] = df['DEAL_YMD'].dt.month

In [5]:
import pandas as pd

def save_dataframe(dataframe, file_path):
    dataframe.to_csv(file_path, index=False)
    print("Dataframe saved successfully!")

In [6]:
save_dataframe(df, 'seoul_real_estate_df.csv')

Dataframe saved successfully!